/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/UploadFileFormData copy.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    IEpDeleteFilled: typeof import('~icons/ep/delete-filled')['default']
    UploadFile: typeof import('./src/components/UploadFile/index.vue')['default']
    UploadFileBase64: typeof import('./src/components/UploadFileBase64.vue')['default']
    UploadFileFormData: typeof import('./src/components/UploadFileFormData.vue')['default']
  }
}
