/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    UploadFile: typeof import('./src/components/UploadFile/index.vue')['default']
    UploadFileBase64: typeof import('./src/components/UploadFileBase64.vue')['default']
    UploadFileFormData: typeof import('./src/components/UploadFileFormData.vue')['default']
    UploadFileLarge: typeof import('./src/components/UploadFileLarge.vue')['default']
    UploadFileMultiple: typeof import('./src/components/UploadFileMultiple.vue')['default']
    UploadFileProgress: typeof import('./src/components/UploadFileProgress.vue')['default']
    UploadFileThumbnail: typeof import('./src/components/UploadFileThumbnail.vue')['default']
  }
}
